# Generated by Django 3.1.1 on 2020-11-25 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0002_pessoa_dt_nasc'),
        ('processo_seletivo', '0007_afiliadoo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Afiliadoo',
            new_name='Afiliado',
        ),
    ]
