# Generated by Django 3.1.1 on 2020-11-25 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processo_seletivo', '0008_auto_20201125_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='afiliado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='processo_seletivo.afiliado'),
        ),
    ]
