# Generated by Django 3.1.2 on 2020-10-13 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('ativo_selecao', models.BooleanField(default=True, verbose_name='Ativo para Seleção')),
                ('ativo_matricula', models.BooleanField(default=True, verbose_name='Ativo para Matrícula')),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('fone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('cpf', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF')),
                ('email_valido', models.BooleanField(default=False)),
                ('fone_valido', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=False)),
                ('codvalidacao', models.CharField(blank=True, max_length=80, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('data_ativacao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pessoa',
            },
        ),
    ]
