# Generated by Django 3.1.2 on 2020-10-13 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import processo_seletivo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituicao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'db_table': 'disciplina',
            },
        ),
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Edição')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Informações')),
                ('dt_ini_insc', models.DateTimeField(blank=True, null=True)),
                ('dt_fim_insc', models.DateTimeField()),
                ('dt_venc_boleto', models.DateField()),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('edital', models.FileField(upload_to='editais', verbose_name='Edital')),
            ],
            options={
                'db_table': 'edicao',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_selecao', models.IntegerField(choices=[(1, 'Processo Seletivo Comum (Prova)'), (2, 'Portador de Diploma (já possui outro curso de nível superior)'), (3, 'Utilizando nota do ENEM')], default=1, verbose_name='Tipo de Ingresso')),
                ('nota_enem', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Nota do Enem')),
                ('ano_enem', models.IntegerField(blank=True, null=True, verbose_name='Ano do Enem')),
                ('comprovante_enem', models.FileField(blank=True, max_length=250, null=True, upload_to=processo_seletivo.models.comprovante_enem_upload_to)),
                ('treineiro', models.BooleanField(default=False)),
                ('comprovante_escolaridade', models.FileField(blank=True, max_length=250, null=True, upload_to=processo_seletivo.models.comprovante_esc_upload_to)),
                ('nec_intlibras', models.BooleanField(default=False)),
                ('nec_ledor', models.BooleanField(default=False)),
                ('nec_transcritor', models.BooleanField(default=False)),
                ('nec_localfacilacesso', models.BooleanField(default=False)),
                ('nec_outros', models.BooleanField(default=False)),
                ('nec_outros_desc', models.TextField(blank=True, null=True, verbose_name='Outras Nec. Especiais')),
                ('nec_prova_presencial', models.BooleanField(default=False)),
                ('dt_agendamento', models.DateTimeField(blank=True, null=True)),
                ('conf_agendamento', models.BooleanField(default=False)),
                ('nota_geral', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True, verbose_name='Nota Geral')),
                ('nota_redacao', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True, verbose_name='Nota Redação')),
                ('nota_redacao_p1', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True, verbose_name='Nota Redação')),
                ('nota_redacao_p2', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True, verbose_name='Nota Redação')),
                ('nota_redacao_p3', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True, verbose_name='Nota Redação')),
                ('nota_redacao_p4', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True, verbose_name='Nota Redação')),
                ('nota_redacao_p5', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True, verbose_name='Nota Redação')),
                ('nota_prova', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True, verbose_name='Nota Prova')),
                ('redacao', models.TextField(blank=True, null=True, verbose_name='Redação')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('situacao', models.IntegerField(choices=[(1, 'Inscrito'), (11, 'Reprovado (nota abaixo do mínimo)'), (12, 'Reprovado (zerou em alguma nota)'), (13, 'Reprovado (não comprovou enem ou doc. conclusão)'), (21, 'Aprovado'), (31, 'Matriculado')], default=1)),
                ('corretor_redacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cursoopcao_set', to='instituicao.curso')),
                ('curso_final', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cursoselecionado_set', to='instituicao.curso')),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='processo_seletivo.edicao')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='instituicao.pessoa')),
            ],
            options={
                'db_table': 'inscricao',
            },
        ),
        migrations.CreateModel(
            name='QuestaoProva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto Questão')),
                ('tipoquestao', models.IntegerField(choices=[(1, 'Objetiva')], default=1)),
                ('pontos', models.DecimalField(decimal_places=1, default='1', max_digits=10)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='processo_seletivo.disciplina')),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='processo_seletivo.edicao')),
            ],
            options={
                'db_table': 'questaoprova',
            },
        ),
        migrations.CreateModel(
            name='RespostaQuestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto Resposta')),
                ('correta', models.BooleanField(default=False)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='processo_seletivo.questaoprova')),
            ],
            options={
                'db_table': 'respostaquestao',
            },
        ),
        migrations.CreateModel(
            name='RespostaInscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='processo_seletivo.inscricao')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='processo_seletivo.questaoprova')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='processo_seletivo.respostaquestao')),
            ],
            options={
                'db_table': 'respostainscricao',
            },
        ),
        migrations.CreateModel(
            name='EdicaoCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_vagas', models.IntegerField(verbose_name='Qtd.Vagas')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='instituicao.curso')),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='processo_seletivo.edicao')),
            ],
            options={
                'db_table': 'edicaocurso',
            },
        ),
    ]
