# Generated by Django 3.1.2 on 2020-10-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processo_seletivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edicao',
            options={'verbose_name': 'edição', 'verbose_name_plural': 'edições'},
        ),
        migrations.AlterModelOptions(
            name='edicaocurso',
            options={'verbose_name': 'curso/edição', 'verbose_name_plural': 'cursos/Edição'},
        ),
        migrations.AlterModelOptions(
            name='inscricao',
            options={'verbose_name': 'inscrição', 'verbose_name_plural': 'inscrições'},
        ),
        migrations.AlterModelOptions(
            name='questaoprova',
            options={'verbose_name': 'questão da prova', 'verbose_name_plural': 'questões da prova'},
        ),
    ]
