# Generated by Django 3.1.2 on 2020-10-15 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processo_seletivo', '0002_auto_20201015_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='edicao',
            name='pagamento_liberado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edicao',
            name='prova_liberada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='dt_conf_agendamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='dt_fim_prova',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='dt_fim_redacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='dt_ini_prova',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='dt_ini_redacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='fez_prova',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='fez_redacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='quem_confirmou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='confagendamento_user_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
