# Generated by Django 3.1.2 on 2020-10-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo_seletivo', '0004_auto_20201015_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostainscricao',
            name='dt_respondeu',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
