# Generated by Django 3.1.1 on 2020-11-25 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0002_pessoa_dt_nasc'),
        ('processo_seletivo', '0006_edicaocurso_valor_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliadoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de indicação')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='instituicao.pessoa')),
            ],
            options={
                'verbose_name': 'afiliado',
                'verbose_name_plural': 'afiliados',
                'db_table': 'afiliados',
            },
        ),
    ]
