# Generated by Django 3.1.2 on 2021-06-07 17:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('processo_seletivo', '0006_auto_20210607_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questaoprova',
            name='texto',
            field=tinymce.models.HTMLField(verbose_name='Textos Questãos'),
        ),
    ]
