# Generated by Django 3.1.1 on 2021-02-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo_seletivo', '0009_inscricao_afiliado'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='visitas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Visitas'),
        ),
    ]
